import {auth,db,onAuthStateChanged,collection,doc,getDoc,getDocs,query,where,runTransaction,getCurrentProfile,escapeHtml,money,serverTimestamp} from './firebase-core.js';
const $=id=>document.getElementById(id);let profile=null;
function showCita(cita){$('cash-result').innerHTML=`<div class="cash-box"><p><strong>CLIENTE</strong><br>${escapeHtml(cita.cliente||'CLIENTE')}</p><p><strong>TOTAL EN EFECTIVO</strong><br>${money(cita.total)}</p><p><strong>ESTADO CITA</strong><br>${escapeHtml(cita.estado||'')}</p><button id="btn-redeem" class="btn-primary">CONFIRMAR PAGO / CANJEAR</button></div>`;$('btn-redeem').onclick=()=>redeem(cita);}
async function lookup(){const code=$('cash-code').value.trim().toUpperCase();if(code.length!==5){$('cash-result').textContent='EL RADICADO DEBE TENER 5 CARACTERES.';return;}const r=await getDoc(doc(db,'radicados',code));if(!r.exists()){ $('cash-result').textContent='RADICADO NO ENCONTRADO.';return;}const rad=r.data();if(rad.estado!=='activo'){ $('cash-result').textContent='ESTE RADICADO YA FUE UTILIZADO O ESTÁ INACTIVO.';return;}const c=await getDoc(doc(db,'citas',rad.citaId));if(!c.exists()){ $('cash-result').textContent='LA CITA ASOCIADA YA NO EXISTE.';return;}const cita={id:c.id,...c.data(),radicado:code};showCita(cita);}
async function redeem(cita){
  const code=cita.radicado;const radRef=doc(db,'radicados',code);const citaRef=doc(db,'citas',cita.id);const txRef=doc(db,'transacciones',cita.id);
  try{await runTransaction(db,async tx=>{const rad=await tx.get(radRef);const c=await tx.get(citaRef);if(!rad.exists()||rad.data().estado!=='activo')throw new Error('El radicado ya no está disponible.');if(!c.exists())throw new Error('La cita no existe.');if(!['reservada','trabajando'].includes(c.data().estado))throw new Error('La cita no puede cobrarse en este estado.');const finalState=c.data().estado==='trabajando'?'finalizada':'recibida';tx.update(radRef,{estado:'usado',usedAt:serverTimestamp(),usedBy:auth.currentUser.uid});tx.set(txRef,{citaId:cita.id,radicado:code,metodo:'efectivo',total:c.data().total||0,estado:'Pago realizado con éxito',processedBy:auth.currentUser.uid,createdAt:serverTimestamp()});tx.update(citaRef,{estado:finalState,estadoPago:'pagado',paidAt:serverTimestamp(),updatedAt:serverTimestamp()});});$('cash-result').innerHTML='<div class="success-box"><strong>✓ PAGO REALIZADO CON ÉXITO</strong><p>El radicado quedó inutilizado y la cita fue actualizada.</p></div>';$('cash-code').value='';}catch(e){console.error(e);$('cash-result').textContent=e.message||'No se pudo canjear el radicado.';}}
$('lookup-btn').addEventListener('click',lookup);$('cash-code').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();lookup();}});
onAuthStateChanged(auth,async user=>{if(!user)return location.href='login.html';profile=await getCurrentProfile(user);if(!profile||!['dueno','admin','barbero'].includes(profile.role)){alert('No tienes acceso a Caja.');return location.href='home.html';}});
